(() => {
  const api='/api'; let editor, currentPath=''; const token=()=>localStorage.getItem('python-ide-token'); const $=id=>document.getElementById(id); const out=x=>$('terminal-output').textContent=x;
  async function request(path, options={}) { const r=await fetch(api+path,{...options,headers:{'Content-Type':'application/json',...(token()?{Authorization:`Bearer ${token()}`}:{})}}); const d=await r.json().catch(()=>({})); if(!r.ok) throw Error(d.detail||'Request failed'); return d; }
  function auth(path){ request(path,{method:'POST',body:JSON.stringify({username:$('username').value.trim(),password:$('password').value})}).then(d=>{localStorage.setItem('python-ide-token',d.token); show(d.user)}).catch(e=>$('auth-output').textContent=e.message); }
  function show(user){$('auth-screen').classList.add('hidden');$('app-shell').classList.remove('hidden');$('user-label').textContent=`${user.username} (${user.role})`; $('admin-tab').classList.toggle('hidden',user.role!=='admin'); loadFiles();}
  function authView(){$('auth-screen').classList.remove('hidden');$('app-shell').classList.add('hidden');}
  async function loadFiles(){try{const d=await request(`/files${currentPath?`?path=${encodeURIComponent(currentPath)}`:''}`);$('path-label').textContent=currentPath||'/';const box=$('file-tree');box.innerHTML='';d.entries.forEach(x=>{const e=document.createElement('div');e.className='file-item';e.textContent=(x.type==='directory'?'📁 ':'📄 ')+x.name;e.onclick=()=>x.type==='directory'?(currentPath=x.path,loadFiles()):openFile(x.path);box.appendChild(e);});}catch(e){out(e.message)}}
  function ensureEditor(){if(editor)return;require.config({paths:{vs:'https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.52.2/min/vs'}});require(['vs/editor/editor.main'],()=>{editor=monaco.editor.create($('editor'),{value:'# Python IDE\nprint("Hello world")\n',language:'python',theme:'vs-dark',automaticLayout:true,minimap:{enabled:false}})})}
  async function openFile(path){currentPath=path;const d=await request(`/file?path=${encodeURIComponent(path)}`);ensureEditor();editor.setValue(d.content||'');$('path-label').textContent=path;out(`Opened: ${path}`)}
  async function create(kind){const name=prompt(kind==='file'?'File name:':'Folder name:',kind==='file'?'script.py':'new-folder');if(!name)return;const path=currentPath&&!currentPath.includes('.')?`${currentPath}/${name}`:name;await request('/files/create',{method:'POST',body:JSON.stringify({path,kind})});currentPath='';loadFiles()}
  async function admin(){try{const [o,u]=await Promise.all([request('/admin/overview'),request('/admin/users')]);$('overview').innerHTML=`<div>${o.users} users</div><div>${o.admins} admins</div><div>${o.workspaces} workspaces</div>`;$('users-body').innerHTML='';u.users.forEach(x=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${x.username}</td><td><select><option ${x.role==='user'?'selected':''}>user</option><option ${x.role==='admin'?'selected':''}>admin</option></select></td><td>${x.created_at}</td><td><button>Save role</button> <button>Delete</button></td>`;const sel=tr.querySelector('select');tr.querySelectorAll('button')[0].onclick=()=>request(`/admin/users/${encodeURIComponent(x.username)}/role`,{method:'PATCH',body:JSON.stringify({role:sel.value})}).then(admin);tr.querySelectorAll('button')[1].onclick=()=>confirm(`Delete ${x.username}?`)&&request(`/admin/users/${encodeURIComponent(x.username)}`,{method:'DELETE'}).then(admin);$('users-body').appendChild(tr)})}catch(e){out(e.message)}}
  window.addEventListener('DOMContentLoaded',async()=>{ensureEditor();$('login-btn').onclick=()=>auth('/auth/login');$('register-btn').onclick=()=>auth('/auth/register');$('logout-btn').onclick=()=>{localStorage.removeItem('python-ide-token');authView()};$('ide-tab').onclick=()=>{$('admin-panel').classList.add('hidden');$('ide-tools').classList.remove('hidden')};$('admin-tab').onclick=()=>{$('admin-panel').classList.remove('hidden');$('ide-tools').classList.add('hidden');admin()};$('reload-users').onclick=admin;$('refresh-btn').onclick=loadFiles;$('new-file-btn').onclick=()=>create('file');$('new-folder-btn').onclick=()=>create('directory');$('save-btn').onclick=()=>request('/files/save',{method:'POST',body:JSON.stringify({path:currentPath,content:editor.getValue()})}).then(()=>out('Saved')).catch(e=>out(e.message));$('run-btn').onclick=()=>request('/run',{method:'POST',body:JSON.stringify({path:currentPath,args:[]})}).then(r=>out(`Exit code: ${r.exit_code}\n${r.stdout}\n${r.stderr}`)).catch(e=>out(e.message));$('pip-btn').onclick=()=>{const p=prompt('Packages, comma separated','requests,pandas');if(p)request('/pip/install',{method:'POST',body:JSON.stringify({packages:p.split(',').map(x=>x.trim())})}).then(r=>out(r.stdout+'\n'+r.stderr)).catch(e=>out(e.message))};if(token())try{show((await request('/auth/me')).user)}catch(_){localStorage.removeItem('python-ide-token');authView()}else authView()});
})();
