(() => {
  const apiRoot = '/api'; let editor; let currentPath = '';
  const token = () => localStorage.getItem('python-ide-token');
  const request = (path, options = {}) => fetch(`${apiRoot}${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(token() ? { Authorization: `Bearer ${token()}` } : {}), ...(options.headers || {}) } }).then(async r => { const data = await r.json().catch(() => ({})); if (!r.ok) throw new Error(data.detail || 'Request failed'); return data; });
  const output = text => { document.getElementById('terminal-output').textContent = text; };
  const authOutput = text => { document.getElementById('auth-output').textContent = text; };
  const credentials = () => ({ username: document.getElementById('username').value.trim(), password: document.getElementById('password').value });
  async function authenticate(path) { try { const data = await request(path, { method: 'POST', body: JSON.stringify(credentials()) }); localStorage.setItem('python-ide-token', data.token); showApp(data.user); } catch (e) { authOutput(e.message); } }
  function showApp(user) { document.getElementById('auth-screen').classList.add('hidden'); document.getElementById('app-shell').classList.remove('hidden'); document.getElementById('user-label').textContent = `${user.username} (${user.role})`; fetchFiles(); }
  function showAuth() { document.getElementById('auth-screen').classList.remove('hidden'); document.getElementById('app-shell').classList.add('hidden'); }
  function renderTree(entries) { const box = document.getElementById('file-tree'); box.innerHTML = ''; entries.forEach(item => { const el = document.createElement('div'); el.className = `file-item ${currentPath === item.path ? 'active' : ''}`; el.textContent = item.type === 'directory' ? `📁 ${item.name}` : `📄 ${item.name}`; el.onclick = () => item.type === 'directory' ? (currentPath = item.path, fetchFiles()) : openFile(item.path); box.appendChild(el); }); }
  async function fetchFiles() { try { const data = await request(`/files${currentPath ? `?path=${encodeURIComponent(currentPath)}` : ''}`); renderTree(data.entries || []); document.getElementById('path-label').textContent = currentPath || '/'; } catch (e) { output(e.message); } }
  function ensureEditor() { if (editor) return; require.config({ paths: { vs: 'https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.52.2/min/vs' } }); require(['vs/editor/editor.main'], () => { editor = monaco.editor.create(document.getElementById('editor'), { value: '# Python IDE\nprint("Hello world")\n', language: 'python', theme: 'vs-dark', automaticLayout: true, minimap: { enabled: false } }); }); }
  async function openFile(path) { currentPath = path; const data = await request(`/file?path=${encodeURIComponent(path)}`); ensureEditor(); const model = monaco.editor.createModel(data.content || '', 'python', monaco.Uri.parse(`file:///${path}`)); editor.setModel(model); document.getElementById('path-label').textContent = path; output(`Opened: ${path}`); }
  async function save() { if (!editor || !currentPath) return output('Select a file first.'); await request('/files/save', { method: 'POST', body: JSON.stringify({ path: currentPath, content: editor.getValue() }) }); output(`Saved: ${currentPath}`); }
  async function run() { if (!currentPath) return output('Select a file first.'); const r = await request('/run', { method: 'POST', body: JSON.stringify({ path: currentPath, args: [] }) }); output(`Exit code: ${r.exit_code}\nSTDOUT:\n${r.stdout || ''}\nSTDERR:\n${r.stderr || ''}`); }
  async function install() { const value = prompt('Packages (comma separated):', 'requests beautifulsoup4 pandas'); if (!value) return; const r = await request('/pip/install', { method: 'POST', body: JSON.stringify({ packages: value.split(',').map(x => x.trim()).filter(Boolean) }) }); output(`Exit code: ${r.exit_code}\n${r.stdout || ''}\n${r.stderr || ''}`); }
  async function create(kind) { const name = prompt(kind === 'file' ? 'File name:' : 'Folder name:', kind === 'file' ? 'script.py' : 'new-folder'); if (!name) return; const path = currentPath && !currentPath.includes('.') ? `${currentPath}/${name}` : name; await request('/files/create', { method: 'POST', body: JSON.stringify({ path, kind }) }); currentPath = ''; fetchFiles(); }
  window.addEventListener('DOMContentLoaded', async () => { document.getElementById('login-btn').onclick = () => authenticate('/auth/login'); document.getElementById('register-btn').onclick = () => authenticate('/auth/register'); document.getElementById('logout-btn').onclick = () => { localStorage.removeItem('python-ide-token'); showAuth(); }; document.getElementById('save-btn').onclick = save; document.getElementById('run-btn').onclick = run; document.getElementById('pip-btn').onclick = install; document.getElementById('new-file-btn').onclick = () => create('file'); document.getElementById('new-folder-btn').onclick = () => create('directory'); document.getElementById('refresh-btn').onclick = fetchFiles; ensureEditor(); if (token()) { try { const data = await request('/auth/me'); showApp(data.user); } catch (_) { localStorage.removeItem('python-ide-token'); showAuth(); } } else showAuth(); });
})();
